Add height weight validations
opensrp/opensrp-client-growth-monitoring pull request #88
Opened 2021-11-29 10:57 UTC by hamza-vd

See this [issue](https://github.com/opensrp/opensrp-client-unicef-tunisia/issues/149)

2021-11-29 13:51 UTC, qiarie commented on opensrp-growth-monitoring/src/main/res/values/strings.xml
> +    <string name="height_is_required">"Child height should not be less than 0cm and not above 100 cms."</string>
Remove the quotes from the string definition

2021-11-29 13:54 UTC, hamza-vd commented on opensrp-growth-monitoring/src/main/res/values/strings.xml
> +    <string name="height_is_required">"Child height should not be less than 0cm and not above 100 cms."</string>
Removed

2021-11-29 14:04 UTC, dubdabasoduba approved these changes

2021-11-29 14:04 UTC, dubdabasoduba commented on opensrp-growth-monitoring/src/main/java/org/smartregister/growthmonitoring/fragment/RecordGrowthDialogFragment.java
> +                if (height <= 0f || height > 1000f) {
Is this 1000 or 100

2021-11-29 14:05 UTC, dubdabasoduba requested changes
Please check my comment earlier

2021-11-29 14:05 UTC, hamza-vd commented on opensrp-growth-monitoring/src/main/java/org/smartregister/growthmonitoring/fragment/RecordGrowthDialogFragment.java
> +                if (height <= 0f || height > 1000f) {
Let me correct, it.

2021-11-29 14:09 UTC, hamza-vd commented on opensrp-growth-monitoring/src/main/java/org/smartregister/growthmonitoring/fragment/RecordGrowthDialogFragment.java
> +                if (height <= 0f || height > 1000f) {
Its fixed now.

2021-11-29 15:11 UTC, qiarie approved these changes

2021-11-30 07:01 UTC, dubdabasoduba approved these changes

2021-11-30 07:04 UTC, merged